services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=59582302d2494386bcac52e4ec5880a67d8cf167af84634e7916ab626f6fc23b
    ports:
      - '7575:7575'
    networks:
      - app-net

networks:
  app-net:
    external: true
